# Replacing all the packages by debian variants:

# librust-chrono-dev	librust-fern-dev  librust-gumdrop-dev
#


[package]
name = "app-gtk3-debian"
version = "0.1.8-B4"
edition = "2021"
description = "Feed Reader Linux-Gtk3 Application"
license = "LGPL-3"

[[bin]]
name = "grassfeeder"
path = "src/main.rs"



# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
# Note: crates.io does not allow packages to be published with path dependencies
# (path dev-dependencies are ignored).
#
[dependencies]
gui_layer = { path = "../gui_layer", version="0.1.0" }
context = { path = "../context", version="0.1.0" }
fr_core = { path = "../fr_core", version="0.1.0", features = ["ui_gtk", "fr_gtk"] }		#	 , "debian-patch"
resources = { path = "../resources", version="0.1.0"  }
fern = { version = ">=0.6", features = ["colored", "chrono"] }
syslog = "6.0.1"
chrono = ">=0.4.19"
# gumdrop = ">=0.8.1"	#  the debian packages only have 0.7.0
gumdrop = ">=0.7.0"
# log = ">=0.4.14"	# the debian packages only have 0.4.11
log = ">=0.4.11"
# once_cell = ">=1.12.0"	# the debian packages only have 1.9.0
once_cell = ">=1.9.0"
# xdg = ">=2.4.1"		# the debian packages only have 2.2.0-3
xdg = ">=2.2"

##  cannot be found as debian package or too old
rust-i18n = { path = "target/rust-i18n-1.1.1" }
feed-rs = { path = "target/feed-rs-1.2.0/feed-rs"  }	# need to take the old version, this keeps a range for chrono open
quick-xml = { path = "target/quick-xml-0.25.0"  , features = ["encoding"]  }
xmlem = { path = "target/xmlem-0.2.0"}
regex = { path = "target/regex-1.6.0" }
url = { path = "target/rust-url-2.3.0/url" }
uuid = { path = "target/uuid-1.1.0" , features = ["v4"] }
flume = { path = "target/flume-master" }
nanorand = { path = "target/nanorand-rs-0.7.0", features = ["getrandom"], optional = true   }
spin = { path="target/spin-rs-0.9.2" }
ico = { path="target/rust-ico-0.3.0" }
image = { path="target/image-0.24.5" }
jpeg-decoder = { path="target/jpeg-decoder-0.3.0" }
libwebp-image = { path="target/libwebp-image-rs-0.3.0" }
lz4-compression = { path="target/lz4-compression-0.7" }
proc-status  = { path="target/proc-status-0.1.1" }
rusqlite  = { path="target/rusqlite-sys0.25.2" }
textcode  = { path="target/textcode-0.2.2" }
tinybmp  = { path="target/tinybmp-0.4.0" }
tl  = { path="target/tl-0.7.7" }
ureq  = { path="target/ureq-2.6.2" }
usvg  = { path="target/resvg-0.29.0/usvg" }
png  = { path="target/image-png-0.17.5" }
bytemuck  = { path="target/bytemuck-1.7.0" }
exr  = { path="target/exrs-1.5.0" }
bit_field = { path="target/rust-bit-field-0.10.1" }
half  = { path="target/half-rs-1.8.2" }
lebe  = { path="target/lebe-0.5.0" }
libwebp = { path="target/libwebp-rs-0.1.0"  }
libwebp-sys2 = { path="target/libwebp-sys2-rs-0.1.2" }
hashlink = { path="target/hashlink-0.8.0" }
embedded-graphics = { path="target/embedded-graphics-embedded-graphics-v0.7.1" }
az = { path="target/az-v1.1.0" }
micromath = { path="target/micromath-1.1.1" }
rustls = { path="target/rustls-v-0.20.8/rustls" }



[profile.release]
opt-level = 's'     # Optimize for size.
lto = true          # Enable Link Time Optimization
strip = true        # Strip symbols from binary*




[package.metadata.deb]
maintainer = "Marcus <schlegler_marcus@posteo.de>"
copyright = "2022 <schlegler_marcus@posteo.de>"
name = "grassfeeder"
extended-description = "This application polls Feeds (Streams of messages) regularly and presents them in a list of events. Browser Urls of blogs, news sites etc. can be dropped and create a new subscription. It reads Atom and several RSS versions."
section = "web"
priority = "optional"
assets =[
    ["target/release/grassfeeder", "/usr/bin/", "755"],
		["assets/changelog.gz", "/usr/share/doc/grassfeeder/", "0644"],
		["assets/grassfeeder.desktop", "/usr/share/applications/", "0644"],
		["assets/grassfeeder.xpm",     "/usr/share/pixmaps/grassfeeder/", "0644"],
		#	 ["assets/usr/share/pixmaps/grassfeeder/grassfeeder-indicator2.png", "/usr/share/pixmaps/grassfeeder/", "0644"],
]

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
