
[build]
target-dir = "../target"


# Created a complete separate build environment for the debian package, due to
# https://wiki.debian.org/Rust
#[source]
#[source.debian-packages]
#directory = "/usr/share/cargo/registry"
#[source.crates-io]
#replace-with = "debian-packages"
