[package]
name = "resources"
version = "0.1.0"
edition = "2021"

[features]
# g3sources = ["i18_local"]
# default = ["i18_local"]
# g3sources = ["rust-i18n"]

[dependencies]
log = ">=0.4.11"
once_cell = "*"



## ALT
# rust-i18n = { version = ">=1.1.1", optional = true, path="../app-g3sources/target/rust-i18n-1.1.1"   }
## Everything else did not work !           TODO patch this later
rust-i18n = { version = "*", path = "../app-g3sources/target/rust-i18n-1.1.1" }

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
