[package]
name = "resources"
version = "0.1.0"
edition = "2021"

[dependencies]
log = ">=0.4.11"
once_cell = "^1.17.1"
rust-i18n = { version = ">=1.1.4" }


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
