[package]
name = "resources"
version = "0.0.1"
edition = "2021"

[dependencies]
log = "0.4.11"
once_cell = "1.10.0"
rust-i18n = ">=0.6.1"


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
