[package]
name = "resources"
version = "0.1.0"
edition = "2021"


[dependencies]
log = { version = ">=0.4.11", path = "../app-gtk3-debian/target/log-0.4.17" }
rust-i18n = { version = "1.1.1", path = "../app-gtk3-debian/target/rust-i18n-1.1.1" }
once_cell = { version = ">=1.3.1", path = "../app-gtk3-debian/target/once_cell-1.10.0" }


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
