[package]
name = "resources"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.11"
git-version = ">=0.3.5"
rust-i18n = ">=1.0.1"
once_cell = ">=1.12.0"


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
