# Created a complete separate build environment for the debian package, due to 
# https://wiki.debian.org/Rust 



[build]
target-dir = "../target"



[source]
[source.debian-packages]
directory = "/usr/share/cargo/registry"
[source.crates-io]
replace-with = "debian-packages"

