[package]
name = "fr_gtk"
version = "0.1.0"
authors = ["marcus"]
edition = "2018"
description = "Feed Reader fr_gtk description"

[dependencies]
gui_layer = { path = "../gui_layer" }
context = { path = "../context" }
ui_gtk = { path = "../ui_gtk" }
resources = { path = "../resources" }
log = "0.4.11"
fern = { version = "0.6", features = ["colored"] }
flume = "0.10.9"
itertools = "0.10.1"
chrono = ">=0.4.19"
once_cell = ">=1.12.0"
rust-i18n = ">=0.6.1"
gtk = { version = "0.15.5", features = ["v3_24_8"] }
gio = "^0.15.5"
glib = "^0.15.5"
gdk = "^0.15.2"
webkit2gtk = {  version = "0.18.0", default-features = false,  features = [ "v2_28"]  }
gdk-sys = "^0.15.1"
gdk-pixbuf = ">=0.15.11"


# cargo run  --example icons
[[example]]
name = "icons"
path = "examples/generate_icons.rs"


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
