[package]
name = "fr_gtk"
version = "0.1.0"
authors = ["marcus"]
edition = "2021"
description = "Feed Reader application specific gtk setup"

[features]
legacy3gtk14 = []

[dependencies]
gui_layer = { path = "../gui_layer" }
context = { path = "../context" }
resources = { path = "../resources" }
rust-i18n = { version = "^1.1.1", path = "../app-gtk3-debian/target/rust-i18n-1.1.1" }
ui_gtk = { path = "../ui_gtk", features = ["legacy3gtk14"] }
gio = "=0.14.8"
fern = { version = ">=0.6", features = ["colored", "chrono"] }
# gtk = { package = "gtk",  version = "0.14.3", features = [  "v3_22_30",] } # downgrade for debian integration
log = ">=0.4.11"
once_cell = ">=1.3.1"
gdk = ">=0.14.3"
gtk = { package = "gtk", version = "0.14.3", features = ["v3_22_30"] }
webkit2gtk = { version = "^0.16", path = "../app-gtk3-debian/target/webkit2gtk-rs-webkit2gtk-rs-v0.16.0" }
pango = "^0.14.8"
flume = { version = "0.10.14", path = "../app-gtk3-debian/target/flume-master" }
gdk-sys = ">=0.14"
itertools = "*"


[[example]]
name = "icons"
path = "examples/generate_icons.rs"


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
