[package]
name = "fr_gtk"
version = "0.1.0"
authors = ["marcus"]
edition = "2018"
description = "Feed Reader spplication specific gtk setup"

[dependencies]
gui_layer = { path = "../gui_layer" }
context = { path = "../context" }
ui_gtk = { path = "../ui_gtk" }
resources = { path = "../resources" }
log = "0.4.11"
fern = { version = "0.6", features = ["colored"] }
flume = { version=">=0.10.9", path="../app-gtk3-debian/target/flume-master" }
itertools = "0.10.1"
chrono = ">=0.4.19"
rust-i18n = { version=">=1.0.1", path="../app-gtk3-debian/target/rust-i18n-1.1.1" }
#	once_cell = ">=1.12.0"
once_cell = ">=1.9.0"

# gtk = { version = "0.16.2", features = ["v3_24_30 "] }	#    2023-03 apply this, deprecate ubuntu20?
#	gtk = { version = "0.15.5", features = ["v3_22_30"] }	# backport to ubuntu20
gtk = { version = ">=0.14.3", features = ["v3_22_30"] }	# downgrade for debian integration


#	gdk = "^0.15.2"	# downgrade for debian integration
gdk = ">=0.14.3"
#	gdk-pixbuf = ">=0.15.11"			# downgrade for debian integration
gdk-pixbuf = ">=0.14.0"
# gdk-sys = "^0.15.1"			# downgrade for debian integration
gdk-sys = ">=0.14.0"
#	gio = "^0.15.5"		# downgrade for debian integration
gio = ">=0.14.0"
#	glib = "^0.15.5"		# downgrade for debian integration
glib = ">=0.14.8"

# webkit2gtk = {  version = "0.18.2", default-features = false,  features = [ "v2_36"] , path="../app-gtk3-debian/target/webkit2gtk-rs-webkit2gtk-rs-v0.18.2" }
# downgrade for debian repo
webkit2gtk = {  version = "0.16.0", default-features = false,  features = [ "v2_30"]	,  path="../app-gtk3-debian/target/webkit2gtk-rs-webkit2gtk-rs-v0.16.0/"  }



# downgrading the feature for debian integration
# libappindicator = ">=0.7.1"


# cargo run  --example icons
[[example]]
name = "icons"
path = "examples/generate_icons.rs"


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
