[workspace]
members = [
  "context",
  "gui_layer",
  "resources",
  "ui_gtk",
  "fr_gtk",
  "fr_core",
  "testing",
]
exclude = [
  "app-g3sources",
  "app-gtk3-linux",
  "app-gtk3-debian",
  "dd-g3new",
  "dd-g3old",
]
#   "dd-g3mid",



