[workspace]
members = [
  "context",
  "gui_layer",
  "resources",
  "ui_gtk",
  "fr_gtk",
  "fr_core",

]
resolver = "2"


exclude = [
  "testing",
  "app-gtk3-linux",
  "app-gtk3-debian",
  "app-gtk3-ubuntu",
]

