
[build]
target-dir = "../target"

[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "../target/sources-vendored"


# Created a complete separate build environment for the debian package, due to
# https://wiki.debian.org/Rust

