[package]
name = "ui_gtk"
version = "0.1.0"
edition = "2021"

[features]
legacy3gtk14 = []

[dependencies]
gui_layer = { path = "../gui_layer" }
resources = { path = "../resources" }
flume = { version = "0.10.14", path = "../app-gtk3-debian/target/flume-master" }
gdk-sys = ">=0.14"
gdk = ">=0.14.3"
gio = "0.14.8"                                                                                               ##  range must not be opened
webkit2gtk = { version = "^0.16.0", path = "../app-gtk3-debian/target/webkit2gtk-rs-webkit2gtk-rs-v0.16.0" }
base64 = "<=0.13.0"                                                                                          # later
gtk = { package = "gtk", version = "0.14.3", features = ["v3_22_30"] }
log = ">=0.4.11"
serde = { version = "1.0.156", path = "../app-gtk3-debian/target/serde-1.0.156/serde" }
lz4-compression = { version = ">=0.7", path = "../app-gtk3-debian/target/lz4-compression-0.7" }

