[package]
name = "ui_gtk"
version = "0.1.0"
edition = "2021"

[features]
g3modern = ["webkit2gtk_m", "webkit2gtk_sys_m", "glib_m", "gio_m" ]

# g3legacy = ["webkit2gtk_l", "webkit2gtk_sys_l"]
# default = ["g3modern"]

[dependencies]
gui_layer = { path = "../gui_layer" }
resources = { path = "../resources" }

webkit2gtk_m = { package = "webkit2gtk", version = "0.18.2", default-features = false, features = [  "v2_36",], optional = true }
# webkit2gtk_l = { package = "webkit2gtk", version = "0.16.0", default-features = false, features = ["v2_30"], optional = true, path = "../app-gtk3-debian/target/webkit2gtk-rs-webkit2gtk-rs-v0.16.0/" }

webkit2gtk_sys_m = { package = "webkit2gtk-sys", version = ">=0.18.0", optional = true }
# webkit2gtk_sys_l = { package = "webkit2gtk-sys", version = "0.16.0", optional = true, path = "../app-gtk3-debian/target/webkit2gtk-rs-webkit2gtk-rs-v0.16.0/sys" }

glib_m = { package = "glib", version = "0.15.5", optional = true } 
glib_l = { package = "glib", version = "0.14.8", optional = true }   # downgrade for debian repo

gio_m = {package="gio" , version="^0.15.5"  , optional = true  }
gio_l = {package="gio" , version="0.14.8"   , optional = true  }    # downgrade for debian repo



flume = { version = ">=0.10.9", path = "../app-gtk3-debian/target/flume-master" }

# gtk = { version = "0.16.2", features = ["v3_24_30 "] }	#    2023-03 apply this, deprecate ubuntu20?
#	gtk = { version = "0.15.5", features = ["v3_22_30"] }	# backport to ubuntu20
gtk = { version = ">=0.14.3", features = [  "v3_22_30",] } # downgrade for debian repo



#	gdk-sys = "^0.15.1"		# downgrade for debian repo
gdk-sys = ">=0.14"
###	log = "0.4.14"				# downgrade for debian repo
log = ">=0.4.11"
# serde = ">=1.0.133"			# downgrade for debian repo
serde = ">=1.0.130"

lz4-compression = { version = "0.7.0", path = "../app-gtk3-debian/target/lz4-compression-0.7" }

base64 = "^0.13.0"

# downgrading for debian intagration
# libappindicator = ">=0.7.1"
