[package]
name = "app-gtk3-linux"
version = "0.1.3-B3"
edition = "2021"
description = "Feed Reader Linux-Gtk3 Application"
license = "LGPL-3"

[[bin]]
name = "grassfeeder"
path = "src/main.rs"

[dependencies]
gui_layer = { path = "../gui_layer" }
context = { path = "../context" }
fr_core = { path = "../fr_core" , features = ["ui_gtk", "fr_gtk"] }
resources = { path = "../resources"  }
log = ">=0.4.14"
xdg = ">=2.4.1"
once_cell = ">=1.12.0"
rust-i18n = ">=0.6.1"
fern = { version = ">=0.6", features = ["colored", "chrono"] }
chrono = ">=0.4.19"
gumdrop = ">=0.8.1"

[profile.release]
opt-level = 's'     # Optimize for size.
lto = true          # Enable Link Time Optimization
strip = true        # Strip symbols from binary*

[package.metadata.deb]
maintainer = "Marcus <schlegler_marcus@posteo.de>"
copyright = "2022 <schlegler_marcus@posteo.de>"
name = "grassfeeder"
extended-description = "Feed Reader Linux-Gtk3 Application"
changelog = "assets/changelog.txt"
section = "utility"
priority = "optional"
assets =[
    ["target/release/grassfeeder", "usr/bin/", "755"],
		["assets/grassfeeder.desktop", "/usr/share/applications/", "755"],
		["assets/grassfeeder.xpm",     "/usr/share/pixmaps/grassfeeder/", "755"],
		["assets/usr/share/pixmaps/grassfeeder/grassfeeder-indicator2.png", "/usr/share/pixmaps/grassfeeder/", "755"],
]

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"

[package.metadata.appimage]
assets = ["assets/usr"]
auto_link = true
auto_link_exclude_list = [
    "libc.so*",
    "libdl.so*",
    "libpthread.so*",
]

#target/grassfeeder-0.1.3-B1-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /tmp/.mount_grassfNBwHOk/lib64/libm.so.6)
#target/grassfeeder-0.1.3-B1-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/.mount_grassfNBwHOk/lib64/libstdc++.so.6)
#target/grassfeeder-0.1.3-B1-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /tmp/.mount_grassfNBwHOk/lib64/libresolv.so.2)

# Running the  fedora33 built appimage   on LinuxMint
# ./grassfeeder-0.1.3-B1-fedora33.AppImage: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /tmp/.mount_grassfVHo6KP/lib64/librt.so.1)

# Running the  fedora33 built appimage With libpthread  on LinuxMint
# ./grassfeeder-0.1.3-B1_1-fedora.AppImage: symbol lookup error: /tmp/.mount_grassf51bSKc/lib64/libpthread.so.0: undefined symbol: _dl_make_stack_executable, version GLIBC_PRIVATE


[package.metadata.generate-rpm]
assets = [
    	{ source="../target/release/grassfeeder", dest="/usr/bin/grassfeeder", mode="755" },
    	{ source="assets/grassfeeder.desktop", dest="/usr/share/applications/grassfeeder.desktop", mode="755" },
    	{ source="assets/grassfeeder.xpm",     dest="/usr/share/pixmaps/grassfeeder/grassfeeder.xpm", mode="755" },
    	{ source="assets/grassfeeder-logo-128x128-t.png", dest="/usr/share/pixmaps/grassfeeder/grassfeeder.png", mode="755" },
]
[package.metadata.generate-rpm.requires]
alternative = "*"
libatomic = "*"
glibc = ">= 2.32"
libcrypto = "*"
libffi = "*"
libicudata = "*"
libicui18n = "*"
libicuuc = "*"
libjpeg = "*"
libm = "*"
libstemmer = "*"
