[package]
name = "gui_layer"
version = "0.1.0"
authors = ["marcus"]
edition = "2021"

[dependencies]
serde = { version = "1.0.156", features = ["derive"] , path = "../app-gtk3-debian/target/serde-1.0.156/serde"  }
