[package]
name = "fr_core"
version = "0.1.0"
edition = "2021"

[features]
ui-gtk = ["ui_gtk", "fr_gtk"]
legacy3gtk14 = []


[dependencies]
context = { path = "../context" }
resources = { path = "../resources" }
gui_layer = { path = "../gui_layer" }
ui_gtk = { path = "../ui_gtk", optional = true }
fr_gtk = { path = "../fr_gtk", optional = true }
once_cell = "^1.17.1"
log = ">=0.4.11"
glob = ">=0.3.0"
bincode = ">=1.3.3"
regex = ">=1.7.1"
serde = ">=1.0.133"
serde_json = ">=1.0.81"
signal-hook = ">=0.3.15"
chrono = ">=0.4.24"
webbrowser = ">=0.7.1"
rust-i18n = { version = ">=1.1.4" }
fern = { version = "^0.6.2", features = ["colored"] }
flume = { version = ">=0.10.14" }
lz4-compression = "^0.7.0"
rusqlite = { version = ">=0.28.0", features = ["bundled"] }
feed-rs = ">=1.3.0"
tl = ">=0.7.7"
url = ">=2.3.1"
opml = ">=1.1.5"
image = ">=0.24.0"
textcode = ">=0.2.2"
ureq = ">=2.6.2"
ico = ">=0.3.0"
png = ">=0.17.7"
gif = ">=0.12.0"
tinybmp = ">=0.4.0"                                         # =0.3.0 problem with rayon
jpeg-decoder = { version = ">=0.3.0" }                      # ">=0.2.0"
libwebp-image = "0.3.0"
proc-status = ">=0.1.1"
usvg = "0.25"
base64 = "<=0.20.0"                                         #  0.21  wants code adaption on many places

[dev-dependencies]
rand = "0.8.5"
zip = "0.6.3"
fern = { version = "^0.6.2", features = ["colored"] }
xmlparser = ">=0.13.5"

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
