[package]
name = "fr_core"
version = "0.1.0"
edition = "2021"

[features]
ui-gtk = ["ui_gtk", "fr_gtk"]
g3new = []                    #   "dd-g3new"
g3sources = [ "app-g3sources" ]                #  "i18local"

[dependencies]
context = { path = "../context" }
resources = { path = "../resources" }
gui_layer = { path = "../gui_layer" }

### NEU
## PROBLEM:  deactivating this does not prevent using their sub-dependencies.
# dd-g3new = { path = "../dd-g3new", optional = true }
# fr_gtk = { path = "../fr_gtk", optional = true, features = ["g3new"] }
# ui_gtk = { path = "../ui_gtk", optional = true, features = ["g3new"]  }
# rust-i18n = "*"


### ALT
#fr_gtk = { path = "../fr_gtk", optional = true, features = ["g3sources"] }
#ui_gtk = { path = "../ui_gtk", optional = true, features = ["g3sources"]  }
app-g3sources = { path = "../app-g3sources", optional = true }
# app-g3sources = "*"
# dd = "*"
ui_gtk = { path = "../ui_gtk", optional = true }
fr_gtk = { path = "../fr_gtk", optional = true }
# rust-i18n = {  path = "../app-g3sources/target/rust-i18n-1.1.1", optional = true }
rust-i18n = { version = "*", path = "../app-g3sources/target/rust-i18n-1.1.1"  }


base64 = "<=0.13.0"
glob = ">=0.3.0"
bincode = ">=1.3.3"
fern = { version = "*", features = ["colored"] }
log = "*"
once_cell = "*"
regex = "*"
serde = "*"
serde_json = "*"
signal-hook = "*"
chrono = "*"
webbrowser = "*"

[dev-dependencies]
rand = "0.8.5"
zip = "0.6.3"
fern = { version = "=0.6.1", features = ["colored"] }

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
