[package]
name = "fr_core"
version = "0.1.0"
edition = "2021"

[features]
ui-gtk = ["ui_gtk", "fr_gtk"]
legacy3gtk14 = []


[dependencies]
context = { path = "../context" }
resources = { path = "../resources" }
gui_layer = { path = "../gui_layer" }
ui_gtk = { path = "../ui_gtk", optional = true, features = ["legacy3gtk14"] }
fr_gtk = { path = "../fr_gtk", optional = true, features = ["legacy3gtk14"] }

rust-i18n = { version = "1.1.1", path = "../app-gtk3-debian/target/rust-i18n-1.1.1" }
lz4-compression = { version = ">=0.7", path = "../app-gtk3-debian/target/lz4-compression-0.7" }
rusqlite = { version = ">=0.28", path = "../app-gtk3-debian/target/rusqlite-0.28.0", features = [    "bundled",] }
feed-rs = { version = "1.3.0", path = "../app-gtk3-debian/target/feed-rs-1.3.0/feed-rs" }
gif = { version = ">=0.12", path = "../app-gtk3-debian/target/image-gif-0.12.0" }
tl = { version = ">=0.7", path = "../app-gtk3-debian/target/tl-0.7.7" }
usvg = { version = "0.29", path = "../app-gtk3-debian/target/resvg-0.29.0/usvg" }
fern = { version = ">=0.5.8" , path = "../app-gtk3-debian/target/fern-fern-0.6.0" , features = [    "colored",    "chrono",] }
log = { version = ">=0.4.10", path = "../app-gtk3-debian/target/log-0.4.17" }
once_cell = { version = ">=1.3.1", path = "../app-gtk3-debian/target/once_cell-1.10.0" }
regex = { version = ">=1.6", path = "../app-gtk3-debian/target/regex-1.6.0" }
serde = { version = "1.0.156", path = "../app-gtk3-debian/target/serde-1.0.156/serde" }
serde_json = { version = ">=1.0.45", path = "../app-gtk3-debian/target/json-1.0.94" }
chrono = { version = ">=0.4.24", path = "../app-gtk3-debian/target/chrono-0.4.24" }
flume = { version = "0.10.14", path = "../app-gtk3-debian/target/flume-master" }
image = { path = "../app-gtk3-debian/target/image-0.24.0" }
ureq = { path = "../app-gtk3-debian/target/ureq-2.6.2" }
webbrowser = ">=0.5.2-2"
base64 = "^0.13.0"
signal-hook = { version = ">=0.3.13-2", path = "../app-gtk3-debian/target/signal-hook-0.3.15" }
opml = { path = "../app-gtk3-debian/target/opml/opml_api" }
bincode = { version=">=1.3.3", path = "../app-gtk3-debian/target/bincode-1.3.3" }
rayon = { path = "../app-gtk3-debian/target/rayon-1.5.1" }
jpeg-decoder = { path = "../app-gtk3-debian/target/jpeg-decoder-0.3.0", features = [    "platform_independent",] }
libwebp-image = { path = "../app-gtk3-debian/target/libwebp-image-rs-0.3.0" }
png = { path = "../app-gtk3-debian/target/image-png-0.17.5" }
proc-status = { path = "../app-gtk3-debian/target/proc-status-0.1.1" }
tinybmp = { path = "../app-gtk3-debian/target/tinybmp-0.4.0" }
textcode = { path = "../app-gtk3-debian/target/textcode-0.2.2" }
url = { path = "../app-gtk3-debian/target/rust-url-2.3.0/url" }
ico = { path = "../app-gtk3-debian/target/rust-ico-0.3.0" }


[dev-dependencies]
rand = "0.8.5"
zip = "0.6.3"

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
