[package]
name = "fr_core"
version = "0.1.0"
edition = "2021"

[features]
ui-gtk = ["ui_gtk", "fr_gtk"]
g3modern =  [ "rusqlite_m" , "png_m", "image_m" , "jpeg_decoder_m", "ico_m", "xmlem_m", "usvg_m" ]

[dependencies]
gui_layer = { path = "../gui_layer" }
ui_gtk = { path = "../ui_gtk" , features=["g3modern"] , optional = true }
fr_gtk = { path = "../fr_gtk" ,  features=["g3modern"] , optional = true }
context = { path = "../context" }
resources = { path = "../resources" }

rusqlite_m = { package="rusqlite", optional=true,  version = ">=0.28.0", features = ["bundled"] }
# rusqlite_l = { package="rusqlite", optional=true,  version = "0.25.2", features = ["bundled"], path="../app-gtk3-debian/target/rusqlite-sys0.25.2" }
png_m =  {package="png", optional=true,   version=">=0.17.7"  }
#png_l =  {package="png", optional=true,   version="0.17.5",  path="../app-gtk3-debian/target/image-png-0.17.5" }
image_m = {package="image", optional=true,  version=">=0.24.5" }
# image_l = {package="image", optional=true,  version=">=0.24.2", path="../app-gtk3-debian/target/image-0.24.5" }
jpeg_decoder_m = { package="jpeg-decoder", optional=true, version=">=0.3" }
# jpeg_decoder_l = { package="jpeg-decoder", optional=true, version="=0.1.22", path="../app-gtk3-debian/target/jpeg-decoder-0.3.0" }
ico_m = { package="ico", optional=true, version=">=0.3.0"}
#ico_l = { package="ico", optional=true, version="0.1.0", path="../app-gtk3-debian/target/rust-ico-0.3.0" }

# usvg = "0.23.0"	# compile error with 0.24.0. https://github.com/RazrFalcon/resvg/issues/552
usvg_m  = {  package="usvg", optional=true,  version="0.23"}  ## downgrading for now. Later: upgrade and adapt the code
# usvg_l  = {  package="usvg", optional=true,  version=">0.24",  path="../app-gtk3-debian/target/resvg-0.29.0/usvg" }


# xmlem = "=0.2.2"	# Produces error:
# error[E0599]: no method named `unescape_value` found for struct `Attribute` in the current scope
# .cargo/registry/src/github.com-1ecc6299db9ec823/xmlem-0.2.2/src/document.rs:373:42
#    373 |                         let value = attr.unescape_value().unwrap();
xmlem_m = { package="xmlem", optional=true, version=">=0.2.3"}
# xmlem_l = { package="xmlem", optional=true, version="=0.2.0",  path = "../app-gtk3-debian/target/xmlem-0.2.0"}




flume = { version=">=0.10.9", path="../app-gtk3-debian/target/flume-master" }
## todo  1.3 available
feed-rs = {version=">=1.1.0", path="../app-gtk3-debian/target/feed-rs-1.2.0/feed-rs" }
libwebp-image = {  version= "0.3.0" , path="../app-gtk3-debian/target/libwebp-image-rs-0.3.0" }
# log = "0.4.14"	# Downgrade for debian repo
log = ">=0.4.11"
lz4-compression =  {  version= "0.7.0" , path="../app-gtk3-debian/target/lz4-compression-0.7" }
# once_cell = ">=1.12.0" # Downgrade for debian repo
once_cell = ">=1.9"

opml ={  version=">=1.1.3" ,  path="../app-gtk3-debian/target/opml/opml_api" }

proc-status = {  version=  ">=0.1.1",  path="../app-gtk3-debian/target/proc-status-0.1.1" }
# regex = ">=1.5.6"		# Downgrade for debian repo
regex = ">=1.5.4"
rust-i18n = { version =  ">=1.0.1", path="../app-gtk3-debian/target/rust-i18n-1.1.1" }
# serde = ">=1.0.137"		# Downgrade for debian repo
serde = ">=1.0.130"
# serde_json = ">=1.0.81"		# Downgrade for debian repo
serde_json = ">=1.0.45"
# signal-hook = ">=0.3.14"		# Downgrade for debian repo
signal-hook = ">=0.3.13"
textcode = { version=">=0.2.2", path="../app-gtk3-debian/target/textcode-0.2.2" }
tinybmp = { version= ">=0.3.3" , path="../app-gtk3-debian/target/tinybmp-0.4.0" }
tl = { version=  ">=0.7.5",  path="../app-gtk3-debian/target/tl-0.7.7" }
ureq = { version=  ">=2.4.0",  path="../app-gtk3-debian/target/ureq-2.6.2" }
url = { version=">=2.2.2",  path = "../app-gtk3-debian/target/rust-url-2.3.0/url" }
#	webbrowser = ">=0.7.1"			# Downgrade for debian repo
webbrowser = ">=0.5"
# xmlparser = ">=0.13.5"				# Downgrade for debian repo
xmlparser = ">=0.11"
# gif = ">=0.12.0"	# Downgrade for debian repo
gif = ">=0.10.2"




glob = ">=0.3.0"
fern = { version = "0.6", features = ["colored"] }
chrono = ">=0.4.19"
bincode = ">=1.3.3"
base64 = "^0.13.0"






[dev-dependencies]
rand = "0.8.5"
# mockall = "0.11.0"
zip = "0.6.3"

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
