[package]
name = "fr_core"
version = "0.1.0"
edition = "2021"


[features]
ui-gtk = ["ui_gtk", "fr_gtk"]

[dependencies]
gui_layer = { path = "../gui_layer" }
ui_gtk = { path = "../ui_gtk" , optional = true }
fr_gtk = { path = "../fr_gtk" , optional = true }
context = { path = "../context" }
resources = { path = "../resources" }

log = "0.4.14"
flume = "0.10.9"
sled = "0.34.7"
feed-rs = "1.1.0"
ureq = "2.4.0"
url = "^2.2.2"
glob = "0.3.0"
opml = "1.1.3"
textcode = ">=0.2.2"
fern = { version = "0.6", features = ["colored"] }
chrono = ">=0.4.19"
# png_pong = ">=0.8.2"
tinybmp = ">=0.3.3"
ico = ">=0.1.0"
jpeg-decoder = ">=0.2"
tl = ">=0.7.5"
usvg = ">=0.23.0"
serde = ">=1.0.137"
serde_json = ">=1.0.81"
bincode = ">=1.3.3"
lz4-compression ="0.7.0"
base64 = "^0.13.0"
libwebp-image = "0.3.0"
image = "0.24.2"
webbrowser = "0.7.1"
once_cell = ">=1.12.0"
rust-i18n = ">=0.6.1"
rusqlite = { version = "0.27.0", features = ["bundled"] }
regex = ">=1.5.6"
proc-status = ">=0.1.1"
png = ">=0.17.6"
gif = ">=0.11.4"

[dev-dependencies]
rand = "0.8.5"
mockall = "0.11.0"


[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
