[package]
name = "fr_core"
version = "0.1.0"
edition = "2021"


[features]
ui-gtk = ["ui_gtk", "fr_gtk"]

[dependencies]
gui_layer = { path = "../gui_layer" }
ui_gtk = { path = "../ui_gtk" , optional = true }
fr_gtk = { path = "../fr_gtk" , optional = true }
context = { path = "../context" }
resources = { path = "../resources" }

log = "0.4.14"
flume = "0.10.9"
feed-rs = "1.1.0"
ureq = "2.4.0"
url = ">=2.2.2"
glob = ">=0.3.0"
opml = ">=1.1.3"
textcode = ">=0.2.2"
fern = { version = "0.6", features = ["colored"] }
chrono = ">=0.4.19"
tinybmp = ">=0.3.3"
ico = ">=0.1.0"
jpeg-decoder = ">=0.2"
tl = ">=0.7.5"
usvg = "0.23.0"	# compile error with 0.24.0. https://github.com/RazrFalcon/resvg/issues/552
serde = ">=1.0.137"
serde_json = ">=1.0.81"
bincode = ">=1.3.3"
lz4-compression ="0.7.0"
base64 = "^0.13.0"
libwebp-image = "0.3.0"
image = ">=0.24.2"
webbrowser = ">=0.7.1"
rusqlite = { version = ">=0.27.0", features = ["bundled"] }
regex = ">=1.5.6"
proc-status = ">=0.1.1"
png = ">=0.17.6"
gif = ">=0.11.4"
xmlparser = ">=0.13.5"
signal-hook = ">=0.3.14"
rust-i18n = ">=1.0.1"
once_cell = ">=1.12.0"

# xmlem = "=0.2.2"	# Produces error:
# error[E0599]: no method named `unescape_value` found for struct `Attribute` in the current scope
# .cargo/registry/src/github.com-1ecc6299db9ec823/xmlem-0.2.2/src/document.rs:373:42
#    373 |                         let value = attr.unescape_value().unwrap();
xmlem = "=0.2.1"





[dev-dependencies]
rand = "0.8.5"
# mockall = "0.11.0"
zip = "0.6.3"

[package.metadata.i18n]
available-locales = ["en", "de"]
default-locale = "en"
